name: CI

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Version
        run: docker version

      - name: Build Docker Images
        run: docker compose build

      - name: Start Docker Containers
        run: docker compose up -d

      - name: Check MySQL connection
        run: |
          until docker compose exec -T db mysqladmin ping -h db --silent; do
            sleep 1
          done

      - name: Install dependencies
        run: docker compose exec app composer install --prefer-dist --no-progress

      - name: Copy .env.example to .env and modify DB_HOST
        run: |
          docker compose exec app cp .env.example .env
          docker compose exec app sed -i "s/DB_HOST=127.0.0.1/DB_HOST=db/g" .env

      - name: Generate APP_KEY
        run: docker compose exec app php artisan key:generate

      - name: Run Database Migrations and Seeds
        run: docker compose exec app php artisan migrate:fresh --seed

      # - name: Run Larastan
      #   run: docker compose exec app ./vendor/bin/phpstan analyse

      # - name: Run PHP-CS-Fixer
      #   run: docker compose exec app ./vendor/bin/php-cs-fixer fix --dry-run --diff

      - name: Run PHPUnit
        run: docker compose exec app ./vendor/bin/phpunit
